/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Attendance = IDL.Record({
  'status' : IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  }),
  'studentId' : IDL.Nat,
  'date' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'department' : IDL.Opt(IDL.Text),
});
export const DashboardStats = IDL.Record({
  'todayAbsentCount' : IDL.Nat,
  'todayLateCount' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'todayPresentCount' : IDL.Nat,
});
export const FeeRecord = IDL.Record({
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
  'studentId' : IDL.Nat,
  'feeType' : IDL.Text,
  'amountPaid' : IDL.Nat,
  'paymentDate' : IDL.Opt(Time),
  'amountDue' : IDL.Nat,
});
export const Result = IDL.Record({
  'totalMarks' : IDL.Nat,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'examName' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'rollNumber' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'employeeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeeRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(Time),
        IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
      ],
      [IDL.Bool],
      [],
    ),
  'addResult' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'addStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTeacher' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAttendanceByDate' : IDL.Func([Time], [IDL.Vec(Attendance)], ['query']),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getFeeRecordsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeeRecord)],
      ['query'],
    ),
  'getResultsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Result)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'markAttendance' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Variant({
          'present' : IDL.Null,
          'late' : IDL.Null,
          'absent' : IDL.Null,
        }),
      ],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateTeacher' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'status' : IDL.Variant({
      'present' : IDL.Null,
      'late' : IDL.Null,
      'absent' : IDL.Null,
    }),
    'studentId' : IDL.Nat,
    'date' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'department' : IDL.Opt(IDL.Text),
  });
  const DashboardStats = IDL.Record({
    'todayAbsentCount' : IDL.Nat,
    'todayLateCount' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'todayPresentCount' : IDL.Nat,
  });
  const FeeRecord = IDL.Record({
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
    'studentId' : IDL.Nat,
    'feeType' : IDL.Text,
    'amountPaid' : IDL.Nat,
    'paymentDate' : IDL.Opt(Time),
    'amountDue' : IDL.Nat,
  });
  const Result = IDL.Record({
    'totalMarks' : IDL.Nat,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'examName' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'rollNumber' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeeRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(Time),
          IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
        ],
        [IDL.Bool],
        [],
      ),
    'addResult' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'addStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTeacher' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAttendanceByDate' : IDL.Func([Time], [IDL.Vec(Attendance)], ['query']),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getFeeRecordsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'getResultsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Result)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'markAttendance' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Variant({
            'present' : IDL.Null,
            'late' : IDL.Null,
            'absent' : IDL.Null,
          }),
        ],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStudent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };