/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'status' : { 'present' : null } |
    { 'late' : null } |
    { 'absent' : null },
  'studentId' : bigint,
  'date' : Time,
}
export interface DashboardStats {
  'todayAbsentCount' : bigint,
  'todayLateCount' : bigint,
  'totalStudents' : bigint,
  'totalTeachers' : bigint,
  'todayPresentCount' : bigint,
}
export interface FeeRecord {
  'status' : { 'pending' : null } |
    { 'paid' : null },
  'studentId' : bigint,
  'feeType' : string,
  'amountPaid' : bigint,
  'paymentDate' : [] | [Time],
  'amountDue' : bigint,
}
export interface Result {
  'totalMarks' : bigint,
  'studentId' : bigint,
  'subject' : string,
  'marksObtained' : bigint,
  'examName' : string,
}
export interface Student {
  'id' : bigint,
  'contact' : string,
  'name' : string,
  'grade' : string,
  'rollNumber' : string,
  'parentName' : string,
}
export interface Teacher {
  'id' : bigint,
  'contact' : string,
  'subject' : string,
  'name' : string,
  'employeeId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeeRecord' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      bigint,
      [] | [Time],
      { 'pending' : null } |
        { 'paid' : null },
    ],
    boolean
  >,
  'addResult' : ActorMethod<[bigint, string, string, bigint, bigint], boolean>,
  'addStudent' : ActorMethod<[string, string, string, string, string], bigint>,
  'addTeacher' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudent' : ActorMethod<[bigint], boolean>,
  'deleteTeacher' : ActorMethod<[bigint], boolean>,
  'getAttendanceByDate' : ActorMethod<[Time], Array<Attendance>>,
  'getAttendanceByStudent' : ActorMethod<[bigint], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getFeeRecordsByStudent' : ActorMethod<[bigint], Array<FeeRecord>>,
  'getResultsByStudent' : ActorMethod<[bigint], Array<Result>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listTeachers' : ActorMethod<[], Array<Teacher>>,
  'markAttendance' : ActorMethod<
    [
      bigint,
      Time,
      { 'present' : null } |
        { 'late' : null } |
        { 'absent' : null },
    ],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStudent' : ActorMethod<
    [bigint, string, string, string, string, string],
    boolean
  >,
  'updateTeacher' : ActorMethod<
    [bigint, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];